name: push

on:
  push:
    branches: [main]

jobs:
  test-build-publish-release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - name: 🚧 Build
        run: npm run build
      - name: 🧪 Test
        run: npm test
      - name: 📢 Release
        uses: tobua/release-npm-action@v3
        with:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
